"""drop tables topics and messages

Revision ID: 0538a4711ea2
Revises: 86eacc08f5a3
Create Date: 2026-10-02 11:12:33.206339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0538a4711ea2'
down_revision: Union[str, Sequence[str], None] = '86eacc08f5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('messages')
    op.drop_table('topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], name=op.f('messages_topic_id_fkey')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_topic_id'), 'messages', ['topic_id'], unique=False)
    op.create_table('topics',
    sa.Column('topic_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['topics.topic_id'], name=op.f('topics_user_id_fkey')),
    sa.PrimaryKeyConstraint('topic_id', name=op.f('topics_pkey'))
    )
    # ### end Alembic commands ###
