"""delete messages table

Revision ID: 9331f0b86966
Revises: 278c42aef950
Create Date: 2026-09-18 22:58:46.247557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9331f0b86966'
down_revision: Union[str, Sequence[str], None] = '278c42aef950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_topic_id'), table_name='messages')
    op.drop_table('messages')
    op.add_column('topics', sa.Column('messages', sa.String(length=1000), nullable=False))
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('topics', 'messages')
    op.create_table('messages',
    sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], name=op.f('messages_topic_id_fkey')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_topic_id'), 'messages', ['topic_id'], unique=False)
    # ### end Alembic commands ###
