"""update table topics, drop messages column

Revision ID: cb35ff84763a
Revises: 85ac217a53dc
Create Date: 2026-09-18 23:08:36.548960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb35ff84763a'
down_revision: Union[str, Sequence[str], None] = '85ac217a53dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('messages', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
